spring:
  datasource:
    url: jdbc:mysql://localhost/gush
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: NON_NULL

doma:
  dialect: mysql
  sql-file-repository: no_cache